### ISSUE TITLE
Cannot cast to StrictMockHandler

### ISSUE THREAD

**Issue by tahmidmozaffar** [benjiman/test-examples#1]
Hello, I am trying to use you example in my test to setup a strict behavior using mockito. But I get an exception message in MockUtils class executing this line....
`
StrictMockHandler handler=  (StrictMockHandler)MockUtil.getMockHandler(mock).getMockSettings().getDefaultAnswer();
`

The exception message is...

> java.lang.ClassCastException: org.mockito.Answers cannot be cast to com.infolytx.hintoncna.utils.MockUtils$StrictMockHandler

How to overcome this error? Any help you can provide? Thank you in advance.

**Comment by benjiman** [comment]
It sounds like you're trying to use verifyNoUnstubbedInteractions on a normal Mockito mock. You need one created with strictMock(Foo.cls). See this example https://github.com/benjiman/test-examples/blob/master/src/test/java/uk/co/benjiweber/testexamples/StrictMockExampleTest.java#L15

Or do it yourself by copying the implementation of strictMock https://github.com/benjiman/test-examples/blob/master/src/main/java/uk/co/benjiweber/mockito/MockUtils.java#L11

If that doesn't work could you provide a small testcase illustrating the problem?

**Comment by tahmidmozaffar** [comment]
Yes you are right. I was trying to do with mock(Foo.class). Now I have done it right and my test is passed. 

But I don't understand one thing....

https://github.com/receme/StrictMock/blob/master/app/src/test/java/com/rcmapps/strictmockito/MainPresenterTest.java#L25

Here, if i remove these two lines....
`Mockito.doNothing().when(mockView).performLogin();`
`Mockito.doNothing().when(mockView).showMainView();`
The test is failing. why is that? Is it not enough to verify these method? why I have to make stub also?

**Comment by benjiman** [comment]
No that's not what its for. If younare verifying things anyway then you can use the verifyNoMoreInteractions that comes with Mockito. This just checks there are no interactions with your mock that were unstubbed. So you could omit the verifies if you want.

**Comment by tahmidmozaffar** [comment]
Ok. I understand now. Thank you.
